services:
  php:
    image: php:8.3-fpm
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network
    container_name: tlyn-php

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network
    container_name: tlyn-nginx
    restart: unless-stopped


  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 123
    ports:
      - "3308:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - app-network
    container_name: tlyn-mysql
    restart: unless-stopped


  redis:
    image: redis:latest
    ports:
      - "6380:6379"
    volumes:
      - ./redis:/data
    networks:
      - app-network
    container_name: tlyn-redis
    restart: unless-stopped

  horizon:
    image: php:8.3-fpm
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/var/www/html
    networks:
      - app-network
    depends_on:
      - mysql
      - redis
    command: php artisan horizon
    container_name: tlyn-horizon
    restart: unless-stopped


volumes:
  mysql:
  redis:

networks:
  app-network:
    driver: bridge
